name: integration

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      display: true
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1-mesa
      envs: |
        - linux: py310-glue_jupyter
        - linux: py310-glue_astronomy
        - linux: py310-glue_wwt
        - linux: py310-glue_vispy_viewers
        - linux: py310-jdaviz
